SELECT UNNEST([1, 1, 1, 2])
UNION
SELECT UNNEST([1, 1, 3]);

SELECT UNNEST([1, 1, 1, 2])
UNION ALL
SELECT UNNEST([1, 1, 3]);



SELECT UNNEST([1, 1, 1, 2])
INTERSECT
SELECT UNNEST([1, 1, 3]);
--1

SELECT UNNEST([1, 1, 1, 2])
INTERSECT ALL
SELECT UNNEST([1, 1, 3]);
--1 , 1 


SELECT UNNEST([1, 1, 1, 2])
EXCEPT
SELECT UNNEST([1, 1, 3]);
--2

SELECT UNNEST([1, 1, 1, 2])
EXCEPT ALL
SELECT UNNEST([1, 1, 3]);
--1 , 2



-- DESCRIBE
CREATE OR REPLACE TEMP TABLE jobs_2023 AS
SELECT * EXCLUDE (job_id, job_posted_date)
FROM job_postings_fact
WHERE EXTRACT(YEAR FROM job_posted_date) = 2023;

SELECT * FROM jobs_2023;

CREATE OR REPLACE TEMP TABLE jobs_2024 AS
SELECT * EXCLUDE (job_id, job_posted_date)
FROM job_postings_fact
WHERE EXTRACT(YEAR FROM job_posted_date) = 2024;

SELECT * FROM jobs_2024;

-- WHICH UNIQUE JOBS POSTINGS APPEARED IN EITHER 23 AND 24?


SELECT 
    'jobs_2023' AS table_name,
    COUNT(*)    AS record_count
FROM jobs_2023
UNION
SELECT 
    'jobs_2024' AS table_name,
    COUNT(*) 
FROM jobs_2024;


-- WHICH JOB POSTINGS APPEARED BOTH YEARS, COUNTING DUPLICATES?

SELECT * FROM jobs_2023
UNION ALL
SELECT * FROM jobs_2024;

-- WHICH JOB POSTINGS APPEARED IN 2023 BUT NOT IN 2024?

SELECT * FROM jobs_2023
EXCEPT
SELECT * FROM jobs_2024;

--WHICH JOB POSTINGS FROM 2023 REMAIN AFTER - MATCHING 2024 POSTINGS 1:1?

SELECT * FROM jobs_2023
EXCEPT ALL
SELECT * FROM jobs_2024;

-- WHICH JOB POSTINGS APPEAR IN BOTH 23 AND 24?

SELECT * FROM jobs_2023
INTERSECT
SELECT * FROM jobs_2024;

-- WHICH JOB POSTINGS APPEAR IN BOTH YEARS, PRESERVING DUPLCIATES?

SELECT * FROM jobs_2023
INTERSECT ALL
SELECT * FROM jobs_2024;